import type { Metadata } from 'next';
import { routing } from '@/i18n/routing';

/**
 * Build per-page, locale-aware metadata: title, description, hreflang
 * alternates for every locale, and Open Graph / Twitter tags.
 * The social image comes from app/[locale]/opengraph-image.tsx (generated).
 * URLs are relative — they resolve against `metadataBase` (set in the root layout).
 */
export function pageMetadata(opts: {
  locale: string;
  path: string; // '' for home, '/demo', '/register', …
  title: string;
  description: string;
}): Metadata {
  const { locale, path, title, description } = opts;

  const languages: Record<string, string> = {};
  for (const l of routing.locales) languages[l] = `/${l}${path}`;

  const url = `/${locale}${path}`;
  // Branded image generated by app/[locale]/opengraph-image.tsx.
  const ogImage = `/${locale}/opengraph-image`;

  return {
    title,
    description,
    alternates: { canonical: url, languages },
    openGraph: {
      title,
      description,
      url,
      siteName: 'QRevent',
      type: 'website',
      locale,
      images: [ogImage],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [ogImage],
    },
  };
}
